FROM ibm-semeru-runtimes:open-17-jdk-jammy as builder
WORKDIR /app
COPY ./ /app/
RUN chmod +x mvnw
RUN apt-get update && apt-get install dos2unix && dos2unix mvnw
RUN ./mvnw clean install

FROM ibm-semeru-runtimes:open-17-jre-jammy
COPY --from=builder /app/registry-bot/target/*.jar app.jar

ENTRYPOINT ["java","-jar","/app.jar"]
