services: 
  web-service-1:
    image: registry-web-1
    container_name: registry-web-container-1
    build:
      dockerfile: Dockerfile.web
      context: .
    env_file:
      - common.env
      - web.env
    ports:
      - "8081:8080"

  bot-service-1:
    image: registry-bot-1
    container_name: registry-bot-container-1
    build:
      dockerfile: Dockerfile.bot
      context: .
    env_file:
      - bot.2.env
      - common.env 
    depends_on:
      - web-service-1
    extra_hosts:
      - "host.docker.internal:host-gateway"